openapi: 3.0.0
info:
  title: Music Library API
  version: 1.0.0
  description: API for managing a music library
servers:
  - url: http://localhost:8080/

paths:
  /song:
    post:
      summary: Save a new song
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - group
                - song
              type: object
              properties:
                group:
                  type: string
                  example: Muse
                song:
                  type: string
                  example: Supermassive Black Hole
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                required:
                  - group_id
                  - song_id
                type: object
                properties:
                  group_id:
                    type: string
                    example: 1
                  song_id:
                    type: string
                    example: 1
        '400':
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: "incorrect json"
                example2:
                  value:
                    error: "bad request"
        '408':
          description: request took too long
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: request took too long
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error

  /library:
    get:
      summary: Get the music library
      parameters:
        - name: offset
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: group_id
          in: query
          required: false
          schema:
            type: integer
        - name: group
          in: query
          required: false
          schema:
            type: string
        - name: song_id
          in: query
          required: false
          schema:
            type: integer
        - name: song
          in: query
          required: false
          schema:
            type: string
        - name: release_date
          in: query
          required: false
          schema:
            type: string
        - name: song_text
          in: query
          required: false
          schema:
            type: string
        - name: link
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Group and their songs
          content:
            application/json:
              schema:
                required:
                  - library
                type: object
                properties:
                  library:
                    type: array
                    items:
                      type: array
                      properties:
                        group:
                          type: object
                          properties:
                            group_id:
                              type: integer
                            group_name:
                              type: string
                            song_info:
                              type: array
                              properties:
                                songs:
                                  type: object
                                  properties:
                                    song_id:
                                      type: integer
                                    song_name:
                                      type: string
                                    release_date:
                                      type: string
                                    song_text:
                                      type: string
                                    link:
                                      type: string
                    example:
                      [
                        {
                          "group_id": 1,
                          "group_name": "Muse",
                          "song_info": [
                            {
                              "song_id": 1,
                              "song_name": "Supermassive Black Hole",
                              "release_date": "16.07.2006",
                              "song_text": "Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight",
                              "link": "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
                            }
                          ]
                        }
                      ]
        '400':
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: "offset is not a number"
                example2:
                  value:
                    error: "limit is not a number"
                example3:
                  value:
                    error: "groupID is not a number"
                example4:
                  value:
                    error: "songID is not a number"
                example5:
                  value:
                    error: "release date is invalid"
        '404':
          description: nothing found
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: nothing found
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error

  /song/{id}/text:
    get:
      summary: Get the song text
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Song text
          content:
            application/json:
              schema:
                required:
                  - song_id
                  - song_name
                  - song_text
                type: object
                properties:
                  song_id:
                    type: integer
                    example: 1
                  song_name:
                    type: string
                    example: Supermassive Black Hole
                  song_text:
                    type: string
                    example: Ooh baby, can you hear me moan?\nYou caught me under false pretenses
        '400':
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: "id is empty"
                example2:
                  value:
                    error: "id is invalid"
                example3:
                  value:
                    error: "offset is not a number"
                example4:
                  value:
                    error: "limit is not a number"
        '404':
          description: song not found
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: song not found
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error

  /song/{id}:
    delete:
      summary: Delete a song
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the song
          schema:
            type: integer
      responses:
        '200':
          description: Message
          content:
            application/json:
              schema:
                required:
                  - message
                  - songID
                type: object
                properties:
                  message:
                    type: string
                    example: song deleted
                  songID:
                    type: integer
                    example: 1
        '400':
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: "id is empty"
                example2:
                  value:
                    error: "id is invalid"
        '404':
          description: song not found
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: song not found
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error

    patch:
      summary: Update song data
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the song
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                song_name:
                  type: string
                release_date:
                  type: string
                  example: 16.07.2006
                song_text:
                  type: string
                link:
                  type: string
                  example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
      responses:
        '200':
          description: Song updated successfully
          content:
            application/json:
              schema:
                required:
                  - song_id
                  - update_info
                type: object
                properties:
                  song_id:
                    type: integer
                    example: 1
                  update_info:
                    type: object
                    properties:
                      song_name:
                        type: string
                      release_date:
                        type: string
                      song_text:
                        type: string
                      link:
                        type: string
              example:
                {
                  "songID": 1,
                  "songInfo": {
                    "song_name": "New Name"
                  }
                }
        '400':
          description: bad request
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: "id is empty"
                example2:
                  value:
                    error: "id is invalid"
                example3:
                  value:
                    error: "incorrect json"
                example4:
                  value:
                    error: "release date is invalid"
                example5:
                  value:
                    error: "link is invalid"
                example6:
                  value:
                    error: "no fields to update"
        '404':
          description: song not found
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: song not found
        '500':
          description: internal server error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    type: string
                    example: internal server error